export default [
    { material: 1, vendor:1, Percentage: 33.3 },
    { material: 1, vendor:2, Percentage: 47.2 },
    { material: 1, vendor:3, Percentage: 5.6 },
    { material: 1, vendor:4, Percentage: 33.3 },
    { material: 1, vendor:5, Percentage: 33.3 },
    { material: 1, vendor:6, Percentage: 33.3 },
    { material: 2, vendor:1, Percentage: 33.3 },
    { material: 2, vendor:2, Percentage: 5.6 },
    { material: 2, vendor:3, Percentage: 88.9 },
    { material: 2, vendor:4, Percentage: 33.3 },
    { material: 2, vendor:5, Percentage: 33.3 },
    { material: 2, vendor:6, Percentage: 33.3 },
    { material: 3, vendor:1, Percentage: 33.3 },
    { material: 3, vendor:2, Percentage: 47.2 },
    { material: 3, vendor:3, Percentage: 5.6 },
    { material: 3, vendor:4, Percentage: 33.3 },
    { material: 3, vendor:5, Percentage: 33.3 },
    { material: 3, vendor:6, Percentage: 33.3 },
   ];
  